# TheWalls
Language: en
peaceTimeMins: 15
preGameAutoStartPlayers: 4
preGameAutoStartSeconds: 120
combatRelogTime: 10
relogTime: 90
UHCMode: false
# --------------------------------------
# tournamentMode true will prevent "autostart happening" requires an op / admin to start the game.
tournamentMode: false
# --------------------------------------
# 0-ANYONE, 1-VIP, 2-PRO, 3-LEGENDARY, 4-STAFF
playerJoinRestriction: ANYONE
allowPickTeams: true
# Either diamond or iron walls
diamondWalls: false
ironWalls: false
# --------------------------------------
# --------------------------------------
# clanBattle allows clan naming - which affects team names. restricts to only those with the clan names to join and play.
clanBattle: false
clan-1: clan 1
clan-2: clan 2
clan-3: clan 3
clan-4: clan 4