name: "WallsPopulator"
authors: ["NonSwag", "codename_B", "NeonMaster", "mbaxter", "kabbage"]
version: "2.0"
main: "net.nonswag.fvr.populator.Populator"
description: "An updated version of the original"
website: "https://www.thenextlvl.net"
load: "STARTUP"